name: Shell Script Checker
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.8.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC1004 # exclude some shellcheck warnings
          SHFMT_OPTS: -s # arguments to shfmt
        with:
          sh_checker_comment: true
